substitutions:
  devicename: in_out
  upper_devicename: Livingroom

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  includes:
    - vl53l1x_Component.h
  libraries:
    - "VL53L1x"
# Enable logging
logger: 
  level: info

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "nolan"
  password: "0973063057"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "0973063057"

captive_portal:
i2c:  # example for Wemos LOLIN D2 mini
  # VL53L1X, 0x29
  frequency: 400kHz

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyCustomSensor();
    App.register_component(my_sensor);
    return {my_sensor->tof_1, my_sensor->tof_2};

  sensors:
  - name: ${devicename}_distance1
    accuracy_decimals: 0
    unit_of_measurement: "mm"

  - name: ${devicename}_distance2
    accuracy_decimals: 0
    unit_of_measurement: "mm"

